import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
terrorism_data = pd.read_csv("C:/21885A0415/LetsGrowMore/Task-2/globalterrorismdb_0718dist.csv", encoding='ISO-8859-1')
print("Basic information about the dataset:")
print(terrorism_data.info())
print("First few rows of the dataset:")
print(terrorism_data.head())
terrorism_data.drop(["eventid", "approxdate", "resolution", "location", "summary", "motive", "propcomment", "ransomnote", "related", "addnotes"], axis=1, inplace=True)
terrorism_data.fillna({'latitude': 0, 'longitude': 0}, inplace=True)
plt.figure(figsize=(12, 6))
terrorism_data['iyear'].value_counts().sort_index().plot(kind='line')
plt.title('Number of Terrorist Attacks Over the Years')
plt.xlabel('Year')
plt.ylabel('Number of Attacks')
plt.grid(True)
plt.show()
plt.figure(figsize=(12, 6))
sns.countplot(x='country_txt', data=terrorism_data, order=terrorism_data['country_txt'].value_counts().iloc[:15].index)
plt.title('Top 15 Most Affected Countries by Terrorism')
plt.xticks(rotation=90)
plt.xlabel('Country')
plt.ylabel('Number of Attacks')
plt.show()
plt.figure(figsize=(12, 6))
sns.countplot(x='attacktype1_txt', data=terrorism_data, order=terrorism_data['attacktype1_txt'].value_counts().index)
plt.title('Most Common Types of Terrorist Attacks')
plt.xticks(rotation=90)
plt.xlabel('Attack Type')
plt.ylabel('Number of Attacks')
plt.show()
plt.figure(figsize=(12, 6))
sns.countplot(x='targtype1_txt', data=terrorism_data, order=terrorism_data['targtype1_txt'].value_counts().index)
plt.title('Most Common Types of Targets for Terrorist Attacks')
plt.xticks(rotation=90)
plt.xlabel('Target Type')
plt.ylabel('Number of Attacks')
plt.show()
plt.figure(figsize=(12, 6))
plt.scatter(terrorism_data['longitude'], terrorism_data['latitude'], alpha=0.5)
plt.title('Hot Zones of Terrorism (Latitude vs. Longitude)')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.grid(True)
plt.show()
